"""init

Revision ID: 8d0c9e36dffc
Revises: 
Create Date: 2021-01-10 18:23:57.988491

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8d0c9e36dffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
        sa.Column('expiry_at', sa.DateTime(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('owner', sa.String(), nullable=False),
        sa.CheckConstraint('char_length(key) = 32', name='check_key_len'),
        sa.PrimaryKeyConstraint('id'),
        schema='public',
    )
    op.create_index(op.f('ix_public_api_key_id'), 'api_key', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_api_key_key'), 'api_key', ['key'], unique=True, schema='public')

    op.create_table('url',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
        sa.Column('link', sa.String(), nullable=False),
        sa.Column('uid', sa.String(), nullable=False),
        sa.Column('expiry_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='public',
    )
    op.create_index(op.f('ix_public_url_id'), 'url', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_url_link'), 'url', ['link'], unique=False, schema='public')
    op.create_index(op.f('ix_public_url_uid'), 'url', ['uid'], unique=True, schema='public')

    op.create_table('statistics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
        sa.Column('url_id', sa.Integer(), nullable=False),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.Column('host', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['url_id'], ['public.url.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='public',
    )
    op.create_index(op.f('ix_public_statistics_id'), 'statistics', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_statistics_url_id'), 'statistics', ['url_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_statistics_url_id'), table_name='statistics', schema='public')
    op.drop_index(op.f('ix_public_statistics_id'), table_name='statistics', schema='public')
    op.drop_table('statistics', schema='public')

    op.drop_index(op.f('ix_public_url_uid'), table_name='url', schema='public')
    op.drop_index(op.f('ix_public_url_link'), table_name='url', schema='public')
    op.drop_index(op.f('ix_public_url_id'), table_name='url', schema='public')
    op.drop_table('url', schema='public')

    op.drop_index(op.f('ix_public_api_key_key'), table_name='api_key', schema='public')
    op.drop_index(op.f('ix_public_api_key_id'), table_name='api_key', schema='public')
    op.drop_table('api_key', schema='public')
    # ### end Alembic commands ###
